export const CART_ADD_ITEM = 'CART_ADD_ITEM';
export const CART_REMOVE_ITEMS = 'CART_REMOVE_ITEMS';
export const CART_REMOVE_ITEM = 'CART_REMOVE_ITEM';
export const CART_SAVE_SHIPPING_ADDRESS = 'CART_SAVE_SHIPPING_ADDRESS';

export const CART_SAVE_REQUEST = 'CART_SAVE_REQUEST';
export const CART_SAVE_SUCCESS = 'CART_SAVE_SUCCESS';
export const CART_SAVE_FAIL = 'CART_SAVE_FAIL';

export const CART_GET_DATABASE_REQUEST = 'CART_GET_DATABASE_REQUEST';
export const CART_GET_DATABASE_SUCCESS = 'CART_GET_DATABASE_SUCCESS';
export const CART_GET_DATABASE_FAIL = 'CART_GET_DATABASE_FAIL';
export const CART_CLEAR_AND_ADD_NEW_ITEM = 'CART_CLEAR_AND_ADD_NEW_ITEM';
