export const CUSTOMER_SIGNIN_REQUEST = 'CUSTOMER_SIGNIN_REQUEST';
export const CUSTOMER_SIGNIN_SUCCESS = 'CUSTOMER_SIGNIN_SUCCESS';
export const CUSTOMER_SIGNIN_FAIL = 'CUSTOMER_SIGNIN_FAIL';
export const CUSTOMER_SIGNOUT_SUCCESS = 'CUSTOMER_SIGNOUT_SUCCESS';

export const CUSTOMER_SIGNUP_REQUEST = 'CUSTOMER_SIGNUP_REQUEST';
export const CUSTOMER_SIGNUP_SUCCESS = 'CUSTOMER_SIGNUP_SUCCESS';
export const CUSTOMER_SIGNUP_FAIL = 'CUSTOMER_SIGNUP_FAIL';

export const CUSTOMER_UPDATE_PROFILE_REQUEST = 'CUSTOMER_UPDATE_REQUEST';
export const CUSTOMER_UPDATE_PROFILE_SUCCESS = 'CUSTOMER_UPDATE_SUCCESS';
export const CUSTOMER_UPDATE_PROFILE_FAIL = 'CUSTOMER_UPDATE_FAIL';
export const CUSTOMER_UPDATE_PROFILE_RESET = 'CUSTOMER_UPDATE_FAIL';
