export const DISH_LIST_REQUEST = 'DISH_LIST_REQUEST';
export const DISH_LIST_SUCCESS = 'DISH_LIST_SUCCESS';
export const DISH_LIST_FAIL = 'DISH_LIST_FAIL';

export const DISH_DETAILS_REQUEST = 'DISH_DETAILS_REQUEST';
export const DISH_DETAILS_SUCCESS = 'DISH_DETAILS_SUCCESS';
export const DISH_DETAILS_FAIL = 'DISH_DETAILS_FAIL';

export const DISH_EDIT_REQUEST = 'DISH_EDIT_REQUEST';
export const DISH_EDIT_SUCCESS = 'DISH_EDIT_SUCCESS';
export const DISH_EDIT_FAIL = 'DISH_EDIT_FAIL';
